title: [toofus, vincent.richefeu@3sr-grenoble.fr]
theme: jekyll-theme-leap-day
show_downloads: true

github:
  zip_url: https://github.com/richefeu/toofus/zipball/main
  tar_url: https://github.com/richefeu/toofus/tarball/main
